### PR TITLE
Team 1

### PR DESCRIPTION
**Pull request by ConnorMRyan**

### CODE REVIEW

**Comment by ConnorMRyan** [comment]
Created a base project for teams to use.

**Review by sophiagavrila — COMMENTED** [review]
approved

**Review by sophiagavrila — APPROVED** [review]
review

**Comment by sophiagavrila** [comment]
PR made to incorrect repository (it was supposed to go to `Batch-844-SophiaGavrila` -- please ignore and close @RevatureGentry

**Pull request merged**
